services:
  meilisearch:
    # image: getmeili/meilisearch:latest
    image: getmeili/meilisearch:v1.11.0-rc.2
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
